version: "3.9"

services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    env_file:
      - src/.env
    ports:
      - "8000:8000"
    networks:
      - web
      - network
    command: python manage.py runserver 0.0.0.0:8000

networks:
  web:
    external: true
  network:
    internal: true
