name: Deploy to Kubernetes Cluster

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_job:
    uses: bartoszcholewa/bartoszcholewa-backend/.github/workflows/build.yaml@main
  deploy_to_kubernetes:
    runs-on: ubuntu-latest
    needs: [ build_job ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secret.KUBE_CONFIG_DATA }} | base64 --decode > ${HOME}/.kube/config

      - name: Test Kubernetes Config
        run: kubectl get pods -w