name: Django CI & Posgres Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  django_test:
    name: Test Django project
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./src
    env:
      DJANGO_SECRET_KEY: github-test-key
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: db
      SQL_USER: user
      SQL_PASSWORD: password
      SQL_HOST: localhost
      SQL_PORT: 5432
    services:
      postgres_db:
        image: postgres:14.2-alpine
        env:
          POSTGRES_DB: ${{ env.SQL_DATABASE }}
          POSTGRES_USER: ${{ env.SQL_USER }}
          POSTGRES_PASSWORD: ${{ env.SQL_PASSWORD }}
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.10.5 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test